// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pryLPWeb_DisTerminal.Data;

#nullable disable

namespace pryLPWeb_DisTerminal.Migrations
{
    [DbContext(typeof(TerminalDbContext))]
    partial class TerminalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("pryLPWeb_DisTerminal.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("pryLPWeb_DisTerminal.Models.RegistroTiempo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EncontroEstrella")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaPartida")
                        .HasColumnType("TEXT");

                    b.Property<int>("JugadorId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TiempoJugado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.ToTable("RegistrosTiempos");
                });

            modelBuilder.Entity("pryLPWeb_DisTerminal.Models.RegistroTiempo", b =>
                {
                    b.HasOne("pryLPWeb_DisTerminal.Models.Jugador", "Jugador")
                        .WithMany("RegistrosTiempos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("pryLPWeb_DisTerminal.Models.Jugador", b =>
                {
                    b.Navigation("RegistrosTiempos");
                });
#pragma warning restore 612, 618
        }
    }
}
